version: '3.6'

services:

  pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - 'pg-data-volume:/var/lib/postgresql/data'
      - './docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql'
    command: -c log_min_messages=FATAL


  rabbitmq:
    image: rabbitmq:$RABBITMQ_VERSION
    hostname: rabbitmq
    volumes:
      - './docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'
      - 'rabbitmq-data-volume:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq'
    environment:
      - 'RABBITMQ_LOGS=-'
    ports:
      - $RABBITMQ_MANAGEMENT_LOCAL_PORT:15672


  redis:
    image: redis:6.0.9
    volumes:
      - 'redis-data-volume:/data'


  # This acts as HTTP reverse proxy for all the other containers.
  nginx:
    image: nginx:1.19.4
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/templates:/etc/nginx/templates'
      - './docker/nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem'
      - './docker/nginx/ssl/key.pem:/etc/nginx/ssl/key.pem'
    ports:
      - $PUBLIC_PORT:$PUBLIC_PORT
    environment:
      - 'PORT=$PUBLIC_PORT'
      - 'CREDITORS_HYDRA_URL=http://creditors-login:4444'
      - 'CREDITORS_LOGIN_URL=http://creditors-login:8080'
      - 'CREDITORS_SERVER_URL=http://creditors-server:8080'
      - 'CREDITORS_SWAGGER_UI_URL=http://creditors-swagger-ui:8080'
      - 'NGINX_ENTRYPOINT_QUIET_LOGS=1'
    depends_on:
      - creditors-server
      - creditors-swagger-ui
      - creditors-login


  creditors-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    environment:
      - 'MIN_CREDITOR_ID=4294967296'
      - 'MAX_CREDITOR_ID=8589934591'
      - 'PIN_PROTECTION_SECRET=some-long-string-that-must-be-kept-secret'
      - 'WEBSERVER_PROCESSES=1'
      - 'WEBSERVER_THREADS=3'
      - 'WEBSERVER_PORT=8080'
      - 'OAUTH2_INTROSPECT_URL=http://creditors-login:4445/oauth2/introspect'
      - 'POSTGRES_URL=postgresql://swpt_creditors:swpt_creditors@pg:5432/${POSTGRES_DB}'
      - 'REDIS_URL=redis://redis:6379/1?health_check_interval=30'
      - 'PROTOCOL_BROKER_URL=amqp://guest:guest@rabbitmq:5672'
      - 'PROTOCOL_BROKER_QUEUE=swpt_creditors'
      - 'PROTOCOL_BROKER_PROCESSES=1'
      - 'PROTOCOL_BROKER_THREADS=3'
      - 'PROTOCOL_BROKER_PREFETCH_COUNT=10'
      - 'APP_LOG_LEVEL=warning'
      - 'APP_LOG_FORMAT=json'
      - 'SUBSTITUTE_LOCALHOST_IN_VARS=PROTOCOL_BROKER_URL'
    depends_on:
      - pg


  # The purpose of this container is to create the database schema for
  # the `creditors-server` container, and all the necessary RabbitMQ
  # objects (queues, exchanges, etc.). It has to be run only once, but
  # running it multiple times should not do any harm. Set
  # `SETUP_RABBITMQ_BINDINGS` to anything other than "yes", if you do
  # not want RabbitMQ exchanges and bindings to be (re)configured.
  creditors-server-config:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    environment:
      - 'MIN_CREDITOR_ID=4294967296'
      - 'MAX_CREDITOR_ID=8589934591'
      - 'POSTGRES_URL=postgresql://swpt_creditors:swpt_creditors@pg:5432/${POSTGRES_DB}'
      - 'PROTOCOL_BROKER_URL=amqp://guest:guest@rabbitmq:5672'
      - 'PROTOCOL_BROKER_QUEUE=swpt_creditors'
      - 'APP_LOG_LEVEL=warning'
      - 'APP_LOG_FORMAT=json'
      - 'SETUP_RABBITMQ_BINDINGS=yes'
      - 'SUBSTITUTE_LOCALHOST_IN_VARS=PROTOCOL_BROKER_URL'
    command: configure
    depends_on:
      - pg


  # From the `swagger-ui-image`, runs a Swagger UI cleint for the
  # "Payments Web API".
  creditors-swagger-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: swagger-ui-image
    environment:
      - 'BASE_URL=/creditors-swagger-ui'
      - 'API_ROOT=https://$PUBLIC_HOST/'
      - 'OAUTH2_AUTHORIZATION_URL=https://$PUBLIC_HOST/creditors-hydra/oauth2/auth'
      - 'OAUTH2_TOKEN_URL=https://$PUBLIC_HOST/creditors-hydra/oauth2/token'
      - 'OAUTH2_REFRESH_URL=https://$PUBLIC_HOST/creditors-hydra/oauth2/token'
      - 'OAUTH2_REDIRECT_URL=https://$PUBLIC_HOST/creditors-swagger-ui/oauth2-redirect.html'


  # This container runs an OAuth 2.0 authorization server, which
  # maintains its own user database, and provides UI for user
  # registration, login, and authorization consent.
  creditors-login:
    image: ghcr.io/swaptacular/swpt_login:$SWPT_LOGIN_VERSION
    environment:
      - 'SERVE_PUBLIC_PORT=4444'
      - 'SERVE_ADMIN_PORT=4445'
      - 'SERVE_TLS_ALLOW_TERMINATION_FROM=0.0.0.0/0'
      - 'WEBSERVER_PORT=8080'
      - 'WEBSERVER_PROCESSES=1'
      - 'WEBSERVER_THREADS=3'
      - 'SUBJECT_PREFIX=creditors:'
      - 'TTL_ACCESS_TOKEN=168h'
      - 'TTL_REFRESH_TOKEN=720h'
      - 'SECRETS_SYSTEM=$HYDRA_SYSTEM_SECRET'
      - 'URLS_SELF_ISSUER=https://$PUBLIC_HOST/creditors-hydra/'
      - 'URLS_LOGIN=https://$PUBLIC_HOST/creditors-login/'
      - 'URLS_CONSENT=https://$PUBLIC_HOST/creditors-consent/'
      - 'URLS_ERROR=https://github.com/swaptacular/swpt_login'
      - 'HYDRA_DSN=postgres://hydra_creditors:hydra_creditors@pg/${POSTGRES_DB}?sslmode=disable&max_conns=2&max_idle_conns=1&max_conn_lifetime=30s'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_creditors_login:swpt_creditors_login@pg/${POSTGRES_DB}'
      - 'REDIS_URL=redis://redis:6379/0?health_check_interval=30'
      - 'HYDRA_ADMIN_URL=http://creditors-login:4445'
      - 'SITE_TITLE=Swaptacular'
      - 'STYLE_URL='
      - 'ABOUT_URL=https://swaptacular.github.io/overview'
      - 'RECAPTCHA_PUBLIC_KEY=6Lc902MUAAAAAJL22lcbpY3fvg3j4LSERDDQYe37'
      - 'RECAPTCHA_PIVATE_KEY=6Lc902MUAAAAAN--r4vUr8Vr7MU1PF16D9k2Ds9Q'
      - 'MAIL_SERVER=mail'
      - 'MAIL_PORT=1025'
      - 'MAIL_DEFAULT_SENDER=Swaptacular <no-reply@example.com>'
      - 'API_AUTH2_TOKEN_URL=https://nginx:$PUBLIC_PORT/creditors-hydra/oauth2/token'
      - 'API_RESOURCE_SERVER=https://nginx:$PUBLIC_PORT'
      - 'API_TIMEOUT_SECONDS=5'
      - 'SUPERVISOR_CLIENT_ID=creditors-supervisor'
      - 'SUPERVISOR_CLIENT_SECRET=creditors-supervisor'
      - 'APP_LOG_LEVEL=warning'
      - 'APP_LOG_FORMAT=json'
      - 'HYDRA_LOG_LEVEL=warning'
      - 'HYDRA_LOG_FORMAT=json'
    depends_on:
      - pg
      - redis
      - mail


  # The purpose of this container is to create the database schemas
  # for the `creditors-login` container. It has to be run only once,
  # but running it multiple times should not do any harm.
  creditors-login-config:
    image: ghcr.io/swaptacular/swpt_login:$SWPT_LOGIN_VERSION
    environment:
      - 'HYDRA_DSN=postgres://hydra_creditors:hydra_creditors@pg/${POSTGRES_DB}?sslmode=disable&max_conns=2&max_idle_conns=1&max_conn_lifetime=30s'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_creditors_login:swpt_creditors_login@pg/${POSTGRES_DB}'
    command: configure
    depends_on:
      - pg


  # The purpose of this container is to create a predefined set of
  # OAuth2 clients (like "swagger-ui"). It has to be run only once,
  # but running it multiple times should not do any harm.
  creditors-hydra-config:
    image: ghcr.io/swaptacular/swpt_login:$SWPT_LOGIN_VERSION
    environment:
      - 'HYDRA_ADMIN_URL=http://creditors-login:4445'
    volumes:
      - './docker/hydra:/etc/hydra-config'
    command:
      hydra clients import
      /etc/hydra-config/creditors-supervisor.json
      /etc/hydra-config/swagger-ui.json
      --fake-tls-termination
      --fail-after 5m
    depends_on:
      - creditors-login


  # The `creditors-login` container needs access to a mail server
  # instance. This runs a dummy mail server which is useful only for
  # testing.
  mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - $MAILHOG_LOCAL_PORT:8025


volumes:
  pg-data-volume:
  rabbitmq-data-volume:
  redis-data-volume:
