version: '3.6'

services:

  pg:
    build:
      context: ./docker/pg
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:5432
    # volumes:
    #   - pg-data-volume:/var/lib/postgresql/data

  pg-create-users:
    build:
      context: ./docker/pg
      dockerfile: Dockerfile
    environment:
      - PGPASSWORD=$POSTGRES_PASSWORD
    command:
      psql -h pg -d "$POSTGRES_DB" -U "$POSTGRES_USER" -f /docker-entrypoint-initdb.d/create-users.sql
    depends_on:
      - pg
    restart: on-failure

  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './swpt_creditors:/usr/src/app/swpt_creditors'
    ports:
      - $PORT:$PORT
      - 1$PORT:5555
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONBREAKPOINT=web_pdb.set_trace
      - SQLALCHEMY_DATABASE_URI=postgresql://swpt_creditors:swpt_creditors@pg:5432/${POSTGRES_DB}
    command: develop-run-flask
    depends_on:
      - pg

  tasks:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './swpt_creditors:/usr/src/app/swpt_creditors'
    ports:
      - 2$PORT:5555
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONBREAKPOINT=web_pdb.set_trace
      - SQLALCHEMY_DATABASE_URI=postgresql://swpt_creditors:swpt_creditors@pg:5432/${POSTGRES_DB}
    command: develop-run-tasks --watch '/usr/src/app/swpt_creditors' tasks:broker
    depends_on:
      - pg

  supervisord:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './swpt_creditors:/usr/src/app/swpt_creditors'
    ports:
      - 3$PORT:5555
    env_file: .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONBREAKPOINT=web_pdb.set_trace
      - SQLALCHEMY_DATABASE_URI=postgresql://swpt_creditors:swpt_creditors@pg:5432/${POSTGRES_DB}
    command: supervisord
    depends_on:
      - pg


# volumes:
#   pg-data-volume:
