version: '3.6'

services:

  tests-redis:
    image: redis:$REDIS_VERSION
    env_file: .env
    ports:
      - $REDIS_LOCAL_PORT:6379
    restart: always

  tests-pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - ./docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql
    ports:
      - $POSTGRES_LOCAL_PORT:5432


  tests-config:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    volumes:
      - './swpt_creditors:/usr/src/app/swpt_creditors'
      - './tests:/usr/src/app/tests'
    env_file: .env
    environment:
      - 'POSTGRES_URL=postgresql://swpt_creditors:swpt_creditors@tests-pg:5432/${POSTGRES_DB}'
      - 'REDIS_URL=redis://tests-redis:6379/0?health_check_interval=30'
      - 'PYTHONDONTWRITEBYTECODE=1'
    command: configure
    depends_on:
      - tests-pg
      - tests-redis


  tests-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    volumes:
      - './swpt_creditors:/usr/src/app/swpt_creditors'
    env_file: .env
    environment:
      - 'WEBSERVER_PORT=8080'
      - 'POSTGRES_URL=postgresql://swpt_creditors:swpt_creditors@tests-pg:5432/${POSTGRES_DB}'
      - 'REDIS_URL=redis://tests-redis:6379/0?health_check_interval=30'
      - 'PYTHONDONTWRITEBYTECODE=1'
      - 'PYTHONBREAKPOINT=web_pdb.set_trace'
    ports:
      - $WEBSERVER_PORT:8080
    command: develop-run-flask
    depends_on:
      - tests-config
