version: '3.6'

services:

  pg:
    image: postgres:$POSTGRES_VERSION
    environment:
      - 'POSTGRES_DB=$POSTGRES_DB'
      - 'POSTGRES_USER=$POSTGRES_USER'
      - 'POSTGRES_PASSWORD=$POSTGRES_PASSWORD'
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
      - ./docker/pg/create-users.sql:/docker-entrypoint-initdb.d/create-users.sql


  redis:
    image: redis:6.0.9


  mail:
    # Mailhog is a dummy mail server which is useful for testing.
    image: mailhog/mailhog:v1.0.1
    ports:
      - 8025:8025


  nginx:
    image: nginx:1.19.4
    volumes:
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/templates:/etc/nginx/templates'
      - './docker/nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem'
      - './docker/nginx/ssl/key.pem:/etc/nginx/ssl/key.pem'
    ports:
      - 443:443
    environment:
      - 'CREDITORS_HOST=$CREDITORS_HOST'
    depends_on:
      - hydra
      - login
      - resource-server
      - swagger-ui

  hydra:
    image: oryd/hydra:$HYDRA_VERSION
    command:
      serve all --dangerous-force-http
    environment:
      - 'LOG_LEVEL=debug'
      - 'LOG_FORMAT=json'
      - 'SECRETS_SYSTEM=$HYDRA_SYSTEM_SECRET'
      - 'DSN=postgres://hydra:hydra@pg/${POSTGRES_DB}?sslmode=disable'
      - 'URLS_SELF_ISSUER=https://$CREDITORS_HOST'
      - 'URLS_LOGIN=https://$CREDITORS_HOST/login'
      - 'URLS_CONSENT=https://$CREDITORS_HOST/consent'
      - 'SERVE_ADMIN_PORT=4445'
      - 'SERVE_PUBLIC_CORS_ENABLED=true'
      - 'SERVE_PUBLIC_CORS_DEBUG=false'
      - 'SERVE_PUBLIC_CORS_ALLOWED_ORIGINS=*'
      - 'SERVE_PUBLIC_CORS_ALLOWED_HEADERS=Authorization,Content-Type,X-Requested-With'
      - 'SERVE_PUBLIC_CORS_MAX_AGE=86400'
      - 'OAUTH2_EXPOSE_INTERNAL_ERRORS=true'
      - 'SQA_OPT_OUT=true'
      # - 'LOG_LEAK_SENSITIVE_VALUES=true'
    depends_on:
      - pg


  hydra-migrate:
    image: oryd/hydra:$HYDRA_VERSION
    command:
      migrate sql postgres://hydra:hydra@pg/${POSTGRES_DB}?sslmode=disable --yes
    depends_on:
      - pg
    restart: on-failure


  hydra-config:
    image: oryd/hydra:$HYDRA_VERSION
    environment:
      - 'HYDRA_ADMIN_URL=http://hydra:4445'
    volumes:
      - './docker/hydra:/etc/hydra-config'
    command:
      clients import /etc/hydra-config/creditors-supervisor.json /etc/hydra-config/swagger-ui.json
    depends_on:
      - hydra
    restart: on-failure


  login:
    build:
      context: ./submodules/swpt_login
      dockerfile: Dockerfile
    environment:
      - 'PORT=4488'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_login:swpt_login@pg/${POSTGRES_DB}'
      - 'REDIS_URL=redis://redis:6379/0'
      - 'MAIL_SERVER=mail'
      - 'MAIL_PORT=1025'
      - 'MAIL_DEFAULT_SENDER=Swaptacular <no-reply@example.com>'
      - 'HYDRA_ADMIN_URL=http://hydra:4445'
      - 'SUBJECT_PREFIX=creditors:'
      - 'SUPERVISOR_CLIENT_ID=creditors-supervisor'
      - 'SUPERVISOR_CLIENT_SECRET=creditors-supervisor'
      - 'API_AUTH2_TOKEN_URL=http://hydra:4444/oauth2/token'
      - 'API_RESOURCE_SERVER=http://resource-server:8080'
      - 'API_RESERVE_USER_ID_PATH=/creditors/.creditor-reserve'
      - 'API_USER_ID_FIELD_NAME=creditorId'
      - 'API_TIMEOUT_SECONDS=5'
      - 'OAUTHLIB_INSECURE_TRANSPORT=1'
    command:
      supervisord
    depends_on:
      - pg
      - redis
      - mail
      - hydra


  login-migrate:
    build:
      context: ./submodules/swpt_login
      dockerfile: Dockerfile
    environment:
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_login:swpt_login@pg/${POSTGRES_DB}'
    command: configure
    depends_on:
      - pg
    restart: on-failure


  resource-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    environment:
      - 'GUNICORN_LOGLEVEL=warning'
      - 'GUNICORN_WORKER_CLASS=sync'
      - 'GUNICORN_WORKERS=2'
      - 'GUNICORN_THREADS=1'
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_creditors:swpt_creditors@pg:5432/${POSTGRES_DB}'
      - 'DRAMATIQ_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'DRAMATIQ_PROCESSES=4'
      - 'DRAMATIQ_THREADS=8'
    command: supervisord
    depends_on:
      - pg


  resource-server-config:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-image
    environment:
      - 'SQLALCHEMY_DATABASE_URI=postgresql://swpt_creditors:swpt_creditors@pg:5432/${POSTGRES_DB}'
      - 'DRAMATIQ_BROKER_URL=amqp://guest:guest@localhost:5672'
      - 'MIN_CREDITOR_ID=-9223372036854775808'
      - 'MAX_CREDITOR_ID=9223372036854775807'
    command: configure
    depends_on:
      - pg


  swagger-ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: swagger-ui-image
    environment:
      - 'API_ROOT=https://$CREDITORS_HOST/'
      - 'OAUTH2_AUTHORIZATION_URL=https://$CREDITORS_HOST/oauth2/auth'
      - 'OAUTH2_TOKEN_URL=https://$CREDITORS_HOST/oauth2/token'
      - 'OAUTH2_REFRESH_URL=https://$CREDITORS_HOST/oauth2/token'
      - 'OAUTH2_REDIRECT_URL=https://$CREDITORS_HOST/swagger-ui/oauth2-redirect.html'
      - 'BASE_URL=/swagger-ui'
      - 'SWAGGER_JSON=/openapi.json'
    depends_on:
      - hydra
      - resource-server


volumes:
  pg-data-volume:
