serve:
  proxy:
    port: 4455
  api:
    port: 4456

access_rules:
  matching_strategy: regexp
  repositories:
    - file:///usr/src/app/oathkeeper/rules.json

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true
    redirect:
      enabled: true
      config:
        to: https://www.ory.sh/docs

authenticators:
  noop:
    enabled: true
  oauth2_introspection:
    enabled: true
    config:
      introspection_url: http://hydra:4445/oauth2/introspect
      scope_strategy: hierarchic
      # introspection_request_headers:
      #   x-forwarded-proto: https
      # cache:
      #   enabled: true
      #   ttl: 60s

authorizers:
  allow:
    enabled: true
  deny:
    enabled: true

mutators:
  noop:
    enabled: true
  header:
    enabled: true
    config:
      headers:
        X-Swpt-User-Id: "{{ print .Subject }}"
        X-Swpt-Require-Pin: "{{ print .Extra.scope | splitList \" \" | has \"disable_pin\" | not }}"
